apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-or
  labels:
    app: or-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: or-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: or-api
    spec:
      containers:
      - name: postgres-or
        image: registry.hub.docker.com/caedus41/oreilly-cloud-engineer-postgres:latest 
---
apiVersion: v1
kind: Service
metadata:
  name: orapi-backend
spec:
  type: NodePort
  ports:
    - targetPort: 5432
      port: 5432
  selector:
      name: postgres-or
